<?php /* @var $this Fooman_GoogleAnalyticsPlus_Block_Ajax */?>
<script>
    /* <![CDATA[ */

    var FoomanGoogleAnalytics = Class.create();
    FoomanGoogleAnalytics.prototype = {
        initialize: function(settings){
            this.baseUrl = settings.baseUrl;
            this.pageQuery = settings.pageQuery;
            this.universal = settings.universal;
            this.altUniversal = settings.altUniversal;
            this.useDataLayer = settings.useDataLayer;
        },
        checkoutStep: function(section){
            switch(section) {
                case "cart": return 1;
                case "login": return 2;
                case "billing": return 3;
                case "shipping": return 4;
                case "shipping_method": return 5;
                case "payment": return 6;
                case "review": return 7;
                case "review-placeOrderClicked": return 8;
            }
            return 0;
        },
        trackEvent: function(section){
            var urlToTrack = this.baseUrl + '/' + section + this.pageQuery;
            if (this.universal) {
                <?php echo Mage::helper('googleanalyticsplus')->getCartProductEC(Mage::getSingleton('checkout/session')->getQuote()) ?>
                ga('set', '&cu', '<?php echo Mage::helper('googleanalyticsplus')->getTrackingCurrency(Mage::getSingleton('checkout/session')->getQuote()) ?>');
                ga('ec:setAction','checkout', {'step': this.checkoutStep(section)});
                ga('set', 'dimension1', '<?php echo Mage::app()->getStore()->getCode() ?>'); // Store
                ga('send', 'pageview', urlToTrack);
            }
            if (this.altUniversal) {
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', '&cu', '<?php echo Mage::helper('googleanalyticsplus')->getTrackingCurrency(Mage::getSingleton('checkout/session')->getQuote()) ?>');
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ec:setAction','checkout', {'step': this.checkoutstep(section)});
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'dimension1', '<?php echo Mage::app()->getStore()->getCode() ?>'); // Store
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.send', 'pageview', urlToTrack);
            }
            if (this.useDataLayer) {
                dataLayer.push({'event': section});
            }
        },
        trackActionOption: function(section, option){
            if (this.universal) {
                ga('ec:setAction', 'checkout_option', {'step': this.checkoutStep(section), 'option': option});
                ga('send', 'event', 'Checkout', 'Option');
            }
            if (this.altUniversal) {
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ec:setAction', 'checkout_option', {'step': this.checkoutStep(section), 'option': option});
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.send', 'event', 'Checkout', 'Option');
            }
        }
    };

    var foomanGoogleAnalytics = new FoomanGoogleAnalytics({
            baseUrl: '<?php echo $this->getBasePageName() ?>',
            pageQuery: '<?php echo $this->getPageQuery() ?>',
            universal: '<?php echo $this->isUniversalEnabled() ? $this->getUniversalAccount():'' ?>',
            altUniversal: '<?php echo $this->isUniversalEnabled() ? $this->getAlternativeUniversalAccount():'' ?>',
            useDataLayer: '<?php echo $this->isTagManagerEnabled()?>'
        }
    );

    if (typeof(Accordion) != "undefined") {
        Accordion.prototype.openSection  = Accordion.prototype.openSection.wrap(function(originalOpenSection, section){
            if (typeof section === 'string') {
                var trackelement = section;
            } else {
                var trackelement = section.id;
            }
            trackelement = trackelement.replace('opc-', '');
            foomanGoogleAnalytics.trackEvent(trackelement);
            originalOpenSection(section);
        });
    }

    if (typeof(Checkout) != "undefined") {
        Checkout.prototype.setMethod  = Checkout.prototype.setMethod.wrap(function(originalSave){
            originalSave();
            if (checkout.method == 'guest') {
                foomanGoogleAnalytics.trackEvent('login');
                foomanGoogleAnalytics.trackActionOption('login','guest');
            } else if (checkout.method == 'register') {
                foomanGoogleAnalytics.trackEvent('login');
                foomanGoogleAnalytics.trackActionOption('login','register');
            }
        });
    }

    if (typeof(Review) != "undefined") {
        Review.prototype.save  = Review.prototype.save.wrap(function(originalSave){
            foomanGoogleAnalytics.trackEvent('review-placeOrderClicked');
            originalSave();
        });
    }

    if (typeof(ShippingMethod) != "undefined") {
        ShippingMethod.prototype.save = ShippingMethod.prototype.save.wrap(function(originalSave){
            if (checkout.loadWaiting!=false) return;
            if (this.validate()) {
                var shippingMethodOption = $(shippingMethod.form).select('input[name="shipping_method"][checked]')[0];
                shippingMethodOption = (typeof shippingMethodOption == 'undefined') ? null : shippingMethodOption.value;
                foomanGoogleAnalytics.trackActionOption('shipping_method',shippingMethodOption);
                originalSave();
            }
        });
    }

    if (typeof(Payment) != "undefined") {
        Payment.prototype.save = Payment.prototype.save.wrap(function(originalSave){
            if (checkout.loadWaiting!=false) return;
            if (this.validate()) {
                foomanGoogleAnalytics.trackActionOption('payment',this.currentMethod);
                originalSave();
            }
        });
    }

    /* ]]> */
</script>
