<?php /* @var $this Fooman_GoogleAnalyticsPlus_Block_Universal */?>
<?php if ($this->shouldInclude()): ?>
    <?php $altUniversal = $this->getAlternativeUniversalAccount(); ?>
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','<?php echo $this->getAnalyticsLocation(); ?>','ga');

        ga('create', '<?php echo $this->getUniversalAccount(); ?>',<?php echo $this->getUniversalParams(); ?>);
        ga('require', 'ec');
        <?php if ($altUniversal):?>
            ga('create', '<?php echo $altUniversal; ?>',<?php echo $this->getUniversalParams(true); ?>);
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'ec');
        <?php endif;?>

        <?php if($this->getUniversalAnonymise()):?>
            ga('set', 'anonymizeIp', true);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'anonymizeIp', true);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->getUniversalDisplayAdvertising()):?>
            ga('require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php endif;?>
        <?php endif;?>

    <?php if($this->isCartPage()):?>
        <?php echo Mage::helper('googleanalyticsplus')->getCartProductEC(Mage::getSingleton('checkout/session')->getQuote()) ?>
        ga('set', '&cu', '<?php echo Mage::helper('googleanalyticsplus')->getTrackingCurrency(Mage::getSingleton('checkout/session')->getQuote()) ?>');
        ga('ec:setAction','checkout', {'step': 1}); // cart step
        if ($altUniversal) {
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', '&cu', '<?php echo Mage::helper('googleanalyticsplus')->getTrackingCurrency(Mage::getSingleton('checkout/session')->getQuote()) ?>');
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ec:setAction','checkout', {'step': 1});
        }
    <?php elseif($this->isSuccessPage()):?>
        <?php $order = $this->_getOrder();?>
            /* <![CDATA[ */
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'ec');
        <?php endif;?>

        <?php
            $shipping = Mage::helper('googleanalyticsplus')->convert($order, 'shipping_amount');
            $tax = Mage::helper('googleanalyticsplus')->convert($order, 'tax_amount');
            $revenue =  Mage::helper('googleanalyticsplus')->convert($order, 'grand_total');
            $revenue -= (($this->shouldExcludeShipping())? $shipping : 0);
            $revenue -= (($this->shouldExcludeTax())? $tax : 0);

            $transactionDetails = "{
                'id': '". $this->jsQuoteEscape($order->getIncrementId()) ."',
                'affiliation': '". $this->jsQuoteEscape(Mage::app()->getStore()->getName()) ."',
                'revenue': '". $revenue ."',
                'shipping': '". $shipping ."',
                'tax': '". $tax ."'
            }";
        ?>

        ga('set', '&cu', '<?php echo Mage::helper('googleanalyticsplus')->getTrackingCurrency($order) ?>');
        ga('ec:setAction', 'purchase', <?php echo $transactionDetails?>);
        <?php if ($altUniversal):?>
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', '&cu', '<?php echo Mage::helper('googleanalyticsplus')->getTrackingCurrency($order) ?>');
            ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ec:setAction', 'purchase', <?php echo $transactionDetails?>);
        <?php endif;?>

        <?php foreach ($order->getAllVisibleItems() as $item):?>

            <?php $itemDetails = "{
                'id': '".$this->jsQuoteEscape($item->getSku()) ."',
                'name': '". $this->jsQuoteEscape($item->getName()) ."',
                'price': '". Mage::helper('googleanalyticsplus')->convert($item, 'price', $order->getOrderCurrencyCode()) ."',
                'quantity': '". (int)$item->getQtyOrdered() ."',
                'category': '". $this->jsQuoteEscape($this->getCategory($item)) ."'
                }";
                ?>

            ga('ec:addProduct', <?php echo $itemDetails?>);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.ec:addProduct', <?php echo $itemDetails?>);
            <?php endif;?>
        <?php endforeach;?>
            /* ]]> */
    <?php endif; ?>
    ga('set', 'dimension1', '<?php echo Mage::app()->getStore()->getCode() ?>'); // Store
    ga('send', 'pageview', '<?php echo $this->getPageName(); ?>');
    <?php if ($altUniversal):?>
        ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'dimension1', '<?php echo Mage::app()->getStore()->getCode() ?>'); // Store
        ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.send', 'pageview', '<?php echo $this->getPageName(); ?>');
    <?php endif;?>
    <!-- End Google Analytics -->
    </script>
<?php endif; ?>
